### ISSUE TITLE
Quick note by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [JannikIbsen/Aesthetic-Programming#12]
Perhaps take a look at Benjamin's code (@Epsilon99) may help on the 2d arrays? https://github.com/Epsilon99/AestheticProgrammingCourse/tree/gh-pages/MiniExcercises/MiniEx_6. Btw, I like the trace function that gives a clearer picture on the cell movement and what is it finding. 

Btw, I like the way you tried to combine the concepts from two readings to think about what is art, and what constitutes (generative) art. You particularly drew on Cox's text on the generative code but you haven't explained about the concept of structure and language in relation to your code and your thinking about generative art. To what extend generative art is regarded as harmony and what do you mean by all factors?

**Comment by JannikIbsen** [comment]
I will definitely look into that, difference between a 2D and 3D array should not be that big.

As to the harmony question, what i mean is the question as to how we interpret art or in this case generative art. My claim similar to Geoff Cox is that to fully appreciate art, we need to not only look at the facade, but also take a closer look at the code itself and in this case, with generative art, look at the microtemporal changes that happen in the code.
