### ISSUE TITLE
hey hey..by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [JannikIbsen/Aesthetic-Programming#14]
Nothing show on screen (only a blank screen) on mini ex 7...look forward to playing with it /w

**Comment by JannikIbsen** [comment]
Hey Winnie.

Oh no.

The starting screen should look like this when the window is maximized on a 1920x1080 monitor:

https://i.gyazo.com/362a50e692d8ba206b9d8c08fde79a45.png

Having 1 checkbox in the center of the screen.
