### ISSUE TITLE
Feedback on Mini Ex 3 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [JannikIbsen/Aesthetic-Programming#4]
Hi Jannik,

I have my micro-phone on but somehow it doesn't captured in your program. I like the way how you experiment multi-media with voice input and audio output. 

In terms of experimenting code, it seems you are quite advanced in the class with your example of creating object, introducing text parsing, as well as manage to use different functions in managing code. Keep up with it.

**Comment by JannikIbsen** [comment]
That's strange, i tried it out on both my desktop and Laptop, and it works on both.
